### ISSUE TITLE
Doesn't work as expected

### ISSUE THREAD

**Issue by washaqq** [kid1194/erpnext_expenses#3]
Hi,
There are some problems with the application,

1- Cannot create Expense type;
![resim](https://github.com/kid1194/erpnext_expenses/assets/16055736/e1cc2b42-853c-4a10-9e0d-5c0fff4847f6)

2- Cannot add expense account;
![resim](https://github.com/kid1194/erpnext_expenses/assets/16055736/ea0cde51-5d76-4543-b360-070bf0e322ca)

3- Cannot add expense item;
![resim](https://github.com/kid1194/erpnext_expenses/assets/16055736/3c4591e7-1a75-4670-bef8-2a43b42c7db2)

and so on, couldn't proceed further because every step throws new error.

And here is the versions;
![resim](https://github.com/kid1194/erpnext_expenses/assets/16055736/a6626bc1-228a-4e3e-a5a0-d2929ee46b0c)

i hope you keep developing this, because it is missing in ERPNext.

Best Wishes.

**Comment by kid1194** [comment]
@washaqq Thank you for reporting these bugs..

I apologize for any inconvenience the plugin caused..

I will fix them and get back to you soon..

If you can, please provide more details about all the errors you faced. It will help a lot..

Best regards..

**Comment by kid1194** [comment]
@washaqq Bro, I have done a lot of changes so please give it another try. 

Hopefully it works without any problem, but if you find something please let me know..

Best regards..

**Comment by washaqq** [comment]
@kid1194 thank you for your effort, but i have problems installing it,
i uninstalled the app then run bench update --reset command, then downloaded the app but when i try to install i had errors;
i dont know if this is about me or the app.
sorry for inconvenience.

```
Installing expenses...
An error occurred while installing expenses: Module import failed for Expense Account, the DocType you're trying to open might be deleted.<br> Error: cannot import name 'get_cache' from 'expenses.utils.common' (/home/patrons/frappe-bench/apps/expenses/expenses/utils/common.py)
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1342, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/expenses/expenses/expenses/doctype/expense_account/expense_account.py", line 9, in <module>
    from expenses.utils import get_cached_value
  File "apps/expenses/expenses/utils/__init__.py", line 15, in <module>
    from .meta import *
  File "apps/expenses/expenses/utils/meta.py", line 9, in <module>
    from .common import (
ImportError: cannot import name 'get_cache' from 'expenses.utils.common' (apps/expenses/expenses/utils/common.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 415, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 297, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 287, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1090, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 917, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1279, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 914, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 407, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 492, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 249, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for Expense Account, the DocType you're trying to open might be deleted.<br> Error: cannot import name 'get_cache' from 'expenses.utils.common' (apps/expenses/expenses/utils/common.py)
```

Best regards,

**Comment by washaqq** [comment]
> @kid1194 thank you for your effort, but i have problems installing it, i uninstalled the app then run bench update --reset command, then downloaded the app but when i try to install i had errors; i dont know if this is about me or the app. sorry for inconvenience.
> 
> ```
> Installing expenses...
> An error occurred while installing expenses: Module import failed for Expense Account, the DocType you're trying to open might be deleted.<br> Error: cannot import name 'get_cache' from 'expenses.utils.common' (/home/patrons/frappe-bench/apps/expenses/expenses/utils/common.py)
> Traceback (most recent call last):
>   File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
>     doctype_python_modules[key] = frappe.get_module(module_name)
>   File "apps/frappe/frappe/__init__.py", line 1342, in get_module
>     return importlib.import_module(modulename)
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "apps/expenses/expenses/expenses/doctype/expense_account/expense_account.py", line 9, in <module>
>     from expenses.utils import get_cached_value
>   File "apps/expenses/expenses/utils/__init__.py", line 15, in <module>
>     from .meta import *
>   File "apps/expenses/expenses/utils/meta.py", line 9, in <module>
>     from .common import (
> ImportError: cannot import name 'get_cache' from 'expenses.utils.common' (apps/expenses/expenses/utils/common.py)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "apps/frappe/frappe/commands/site.py", line 415, in install_app
>     _install_app(app, verbose=context.verbose, force=force)
>   File "apps/frappe/frappe/installer.py", line 297, in install_app
>     sync_for(name, force=force, reset_permissions=True)
>   File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
>     import_file_by_path(
>   File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path
>     import_doc(
>   File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
>     doc.insert()
>   File "apps/frappe/frappe/model/document.py", line 287, in insert
>     self.run_post_save_methods()
>   File "apps/frappe/frappe/model/document.py", line 1090, in run_post_save_methods
>     self.run_method("on_update")
>   File "apps/frappe/frappe/model/document.py", line 917, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 1279, in composer
>     return composed(self, method, *args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 1261, in runner
>     add_to_return_value(self, fn(self, *args, **kwargs))
>   File "apps/frappe/frappe/model/document.py", line 914, in fn
>     return method_object(*args, **kwargs)
>   File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 407, in on_update
>     self.run_module_method("on_doctype_update")
>   File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 492, in run_module_method
>     module = load_doctype_module(self.name, self.module)
>   File "apps/frappe/frappe/modules/utils.py", line 249, in load_doctype_module
>     raise ImportError(msg) from e
> ImportError: Module import failed for Expense Account, the DocType you're trying to open might be deleted.<br> Error: cannot import name 'get_cache' from 'expenses.utils.common' (apps/expenses/expenses/utils/common.py)
> ```
> 
> Best regards,


i just checked if there is any remaining doctype, and i found one, but i can not delete it, it is very strange, this may cause the problem.

![image](https://github.com/kid1194/erpnext_expenses/assets/16055736/86c66ef0-0e88-4035-8e46-dc365c2fca0c)

guess what there is also a remaining module;

![image](https://github.com/kid1194/erpnext_expenses/assets/16055736/6b162713-a0d9-4ba8-bfe8-313828b46d96)

and can not delete it either.

**Comment by kid1194** [comment]
@washaqq I apologize to you bro..

I just forgot to modify some files..

Please try it again.

Your patience and trying effort is much appreciated. Only few people who tested this plugin for me and for a short period of time so, I appreciate everything you do..

Best regards..

**Comment by washaqq** [comment]
> @washaqq I apologize to you bro..
> 
> I just forgot to modify some files..
> 
> Please try it again.
> 
> Your patience and trying effort is much appreciated. Only few people who tested this plugin for me and for a short period of time so, I appreciate everything you do..
> 
> Best regards..

don't mention it, :) i accessed to db and deleted leftovers from `tabDocType` and `tabModule Def` tables, i am running `bench update --reset` command now, it takes sometimes, then i will install the app, and i will let you know what is happening.

Best Wishes,

**Comment by washaqq** [comment]
> > @washaqq I apologize to you bro..
> > I just forgot to modify some files..
> > Please try it again.
> > Your patience and trying effort is much appreciated. Only few people who tested this plugin for me and for a short period of time so, I appreciate everything you do..
> > Best regards..
> 
> don't mention it, :) i accessed to db and deleted leftovers from `tabDocType` and `tabModule Def` tables, i am running `bench update --reset` command now, it takes sometimes, then i will install the app, and i will let you know what is happening.
> 
> Best Wishes,

Nope this time i get different error;

```
Installing expenses...
Updating DocTypes for expenses      : [========================================] 100%
An error occurred while installing expenses: name 'frappe' is not defined
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 415, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 307, in install_app
    frappe.get_attr(after_install)()
  File "apps/expenses/expenses/setup/install.py", line 39, in after_install
    _add_link_to_workspace()
  File "apps/expenses/expenses/setup/install.py", line 46, in _add_link_to_workspace
    if frappe.db.exists(dt, name):
NameError: name 'frappe' is not defined
```

hope it is not my mistake :) 

Best Wishes,

**Comment by kid1194** [comment]
@washaqq Sorry buddy, I forgot to import frappe in the install file..😅

By the way, I wanted to show you some appreciation..
![Contributors](https://github.com/kid1194/erpnext_expenses/assets/7622668/880a29b0-9a3b-4cf4-8e1a-b7f6b35847d8)

**Comment by washaqq** [comment]
> @washaqq Sorry buddy, I forgot to import frappe in the install file..😅
> 
> By the way, I wanted to show you some appreciation.. ![Contributors](https://user-images.githubusercontent.com/7622668/271674792-880a29b0-9a3b-4cf4-8e1a-b7f6b35847d8.png)

@kid1194 Thank you for this kind attitude :), i installed successfully, but expense app is lost in account module, took me while to figure it out where is expense app; 
![image](https://github.com/kid1194/erpnext_expenses/assets/16055736/a458059a-e6c4-4890-8b7f-01ffdafa64ac)

not a big deal,

another problem is, i am not sure if it is a problem, because i don't know how it is structured to use, i can not create first expense type if it is not selected as group and can not choose expense account of the selected company, i have to click on edit then i choose the expense account;
![image](https://github.com/kid1194/erpnext_expenses/assets/16055736/b3bcc974-7fd2-49e1-b8ac-a401b1bec381)

did not go further.

**Comment by kid1194** [comment]
@washaqq Thanks a lot buddy for giving this plugin another chance..

The expense type is a tree, so you must create a group first then you can add other types inside the group..

For the expense accounts table, in each row you need to select a company first then you can select an expense account. It's done this way so the expense account field only display the accounts of the selected company only..

If you think that anything in the plugin could be done in a better way, please inform me 😁

Best regards..

**Comment by kid1194** [comment]
@washaqq Hey bro..

I just want to inform you that I have improved the app and fixed a lot of the bugs I found. So if you want, give it another try..

I hope that this time you won't be disappointed..

Best regards..
