### ISSUE TITLE
[BUG]: Installing expenses

### ISSUE THREAD

**Issue by hassan-youssef** [kid1194/erpnext_expenses#5]
**bench --site test.local install-app expenses**

Installing expenses...
An error occurred while installing expenses: No module named 'expenses.utils'
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 311, in install_app
    frappe.get_attr(after_install)()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1705, in get_attr
    return getattr(get_module(modulename), methodname)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/expenses/expenses/setup/install.py", line 15, in <module>
    from expenses.utils import (
ModuleNotFoundError: No module named 'expenses.utils'
ERPNext: v15.8.3 (version-15)

Expenses: v1.0.0 (main)

Frappe Framework: v15.7.0 (version-15)

**Comment by kid1194** [comment]
@hassan-youssef thank you so much bro for reporting this..

I have fixed the problem and I hope that everything works well..

Best regards..

**Comment by hassan-youssef** [comment]
@kid1194
 Installing expenses...
An error occurred while installing expenses: unexpected indent (item.py, line 100)
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 311, in install_app
    frappe.get_attr(after_install)()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1705, in get_attr
    return getattr(get_module(modulename), methodname)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/expenses/expenses/setup/install.py", line 15, in <module>
    from expenses.libs import (
  File "apps/expenses/expenses/libs/__init__.py", line 7, in <module>
    from .account import *
  File "apps/expenses/expenses/libs/account.py", line 17, in <module>
    from .item import __ITEM__
  File "apps/expenses/expenses/libs/item.py", line 100
    .where(doc.expense_type.isin(get_types_filter_query()))
IndentationError: unexpected indent

**Comment by kid1194** [comment]
@hassan-youssef Hey bro..

A million thanks to you for giving the app another try and reporting this..

I have fixed this problem and I hope that you like my token of appreciation 😀

Best regards..

**Comment by hassan-youssef** [comment]
@kid1194 Thanks Another error
Installing expenses...
An error occurred while installing expenses: cannot import name 'get_item_company_account_data' from partially initialized module 'expenses.libs.account' (most likely due to a circular import) (/home/frappe/frappe-bench/apps/expenses/expenses/libs/account.py)
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 311, in install_app
    frappe.get_attr(after_install)()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1705, in get_attr
    return getattr(get_module(modulename), methodname)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/expenses/expenses/setup/install.py", line 15, in <module>
    from expenses.libs import (
  File "apps/expenses/expenses/libs/__init__.py", line 7, in <module>
    from .account import *
  File "apps/expenses/expenses/libs/account.py", line 17, in <module>
    from .item import __ITEM__
  File "apps/expenses/expenses/libs/item.py", line 15, in <module>
    from .account import get_item_company_account_data
ImportError: cannot import name 'get_item_company_account_data' from partially initialized module 'expenses.libs.account' (most likely due to a circular import) (apps/expenses/expenses/libs/account.py)

**Comment by kid1194** [comment]
@hassan-youssef Sorry about that bro, I totally forgot about circular reference 😅

Thanks to you, I fixed it..

Best regards..

**Comment by hassan-youssef** [comment]
Installing expenses...
An error occurred while installing expenses: invalid syntax (check.py, line 84)
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 301, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 111, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 148, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 245, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 310, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1118, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 526, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 624, in run_module_method
    module = load_doctype_module(self.name, self.module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/modules/utils.py", line 241, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/expenses/expenses/expenses/doctype/expenses_request/expenses_request.py", line 16, in <module>
    from expenses.libs import (
  File "apps/expenses/expenses/libs/__init__.py", line 11, in <module>
    from .check import *
  File "apps/expenses/expenses/libs/check.py", line 84
    if name::
            ^
SyntaxError: invalid syntax

**Comment by kid1194** [comment]
@hassan-youssef My apologies to you bro for all the troubles I caused..

I have made some silly mistakes and thanks to you, I fixed them.. 

Best regards..

**Comment by hassan-youssef** [comment]
Installing expenses...
An error occurred while installing expenses: cannot import name 'get_expense_entries' from partially initialized module 'expenses.libs.entry' (most likely due to a circular import) (/home/frappe/frappe-bench/apps/expenses/expenses/libs/entry.py)
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 311, in install_app
    frappe.get_attr(after_install)()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1705, in get_attr
    return getattr(get_module(modulename), methodname)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/expenses/expenses/setup/install.py", line 15, in <module>
    from expenses.libs import (
  File "apps/expenses/expenses/libs/__init__.py", line 14, in <module>
    from .entry import *
  File "apps/expenses/expenses/libs/entry.py", line 28, in <module>
    from .request import get_request
  File "apps/expenses/expenses/libs/request.py", line 14, in <module>
    from .expense import (
  File "apps/expenses/expenses/libs/expense.py", line 23, in <module>
    from .entry import get_expense_entries
ImportError: cannot import name 'get_expense_entries' from partially initialized module 'expenses.libs.entry' (most likely due to a circular import) (apps/expenses/expenses/libs/entry.py)

**Comment by kid1194** [comment]
@hassan-youssef Sorry bro for that..
The problem is because of **circular import**..

Now it's fixed and hopefully it is the last installation error you face..

I'm really thankful for what you are doing and for your great help..

Best regards..

**Comment by hassan-youssef** [comment]
@kid1194 
Installing expenses...
Updating DocTypes for expenses      : [======================                  ] 56%An error occurred while installing expenses: invalid syntax (expense.py, line 46)
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 301, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 111, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 148, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 245, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 310, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1118, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 526, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 624, in run_module_method
    module = load_doctype_module(self.name, self.module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/modules/utils.py", line 241, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/expenses/expenses/expenses/doctype/expense/expense.py", line 46
    if temp[k] && flt(self.get(k)) != temp[k]:
                ^
SyntaxError: invalid syntax

**Comment by kid1194** [comment]
@hassan-youssef Sorry bro, my mistake..

Sometimes I mix syntax from different programming languages and in this I used "&&" instead of "and" which is a JavaScript and PHP syntax 😅

My sincere apologies to you bro for such mistakes..

Please forgive me and give it another try..

Best regards..

**Comment by hassan-youssef** [comment]
@kid1194 
Installing expenses...
Updating DocTypes for expenses      : [===========================             ] 68%An error occurred while installing expenses: Module import failed for Expenses Entry, the DocType you're trying to open might be deleted.<br> Error: cannot import name '__ACCOUNT__' from 'expenses.libs' (/home/frappe/frappe-bench/apps/expenses/expenses/libs/__init__.py)
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 241, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/expenses/expenses/expenses/doctype/expenses_entry/expenses_entry.py", line 17, in <module>
    from expenses.libs import (
ImportError: cannot import name '__ACCOUNT__' from 'expenses.libs' (apps/expenses/expenses/libs/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 301, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 111, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 148, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 245, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 310, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1118, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 526, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 624, in run_module_method
    module = load_doctype_module(self.name, self.module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for Expenses Entry, the DocType you're trying to open might be deleted.<br> Error: cannot import name '__ACCOUNT__' from 'expenses.libs' (apps/expenses/expenses/libs/__init__.py)

**Comment by kid1194** [comment]
@hassan-youssef Hey bro, thanks a lot for reporting this..

This error indicates that frappe was unable to find the **Account** doctype that is part of ERPNext..

So, do you have ERPNext installed?

Best regards..

**Comment by hassan-youssef** [comment]
@kid1194 I sold the installation back to the screens like this
![Screenshot from 2024-01-10 10-57-10](https://github.com/kid1194/erpnext_expenses/assets/60713522/690cad98-f39c-4421-87ea-d70d4bd66e05)

**Comment by hassan-youssef** [comment]
![Screenshot from 2024-01-10 10-57-32](https://github.com/kid1194/erpnext_expenses/assets/60713522/8322e211-8da6-4d28-9e31-32627665874a)

**Comment by kid1194** [comment]
@hassan-youssef Sorry about that bro, a missing "}" caused this..

I have fixed this and updated the app..

Please give it another try and hopefully everything works well..

Thank you bro for everything..

Best regards..

**Comment by hassan-youssef** [comment]
App erpnext already installed

ERPNext: v15.17
Installing expenses...
Skipping fixture syncing from the file workflow.json. Reason: DocType Expenses Request not found
Updating Dashboard for expenses
